### ISSUE TITLE
Cannot set executor

### ISSUE THREAD

**Issue by acristoffers** [colcon/colcon-mixin#45]
Hi,

I have a mixin like this:

```yaml
test:
  integration:
    ctest-args:
      - -L
      - integration
    executor: sequential
    return-code-on-test-failure: true
    event-handlers:
      - console_cohesion+
```

However, I cannot get it to set the executor, and I'm forced to pass `--executor sequential` in the
command line.
